/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlayDotphpRouteImport } from './routes/play[.]php'
import { Route as IndexRouteImport } from './routes/index'

const PlayDotphpRoute = PlayDotphpRouteImport.update({
  id: '/play.php',
  path: '/play.php',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/play.php': typeof PlayDotphpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/play.php': typeof PlayDotphpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/play.php': typeof PlayDotphpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/play.php'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/play.php'
  id: '__root__' | '/' | '/play.php'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayDotphpRoute: typeof PlayDotphpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/play.php': {
      id: '/play.php'
      path: '/play.php'
      fullPath: '/play.php'
      preLoaderRoute: typeof PlayDotphpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayDotphpRoute: PlayDotphpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
